### ISSUE TITLE
Incorrect display in Firefox for Android

### ISSUE THREAD

**Issue by Ravenbird** [writeas/writefreely#339] opened 2020-07-28 09:51 UTC
Hello,

i'm using the WriteFreely instance on wordsmith.social and I have a problem in Firefox for Android that a menu is displayed incorrectly. This looks like this:

![](https://i.ibb.co/DC2L85S/Screenshot-20200727-101547.jpg)

The problem does not occur with chrome on Android.  And the Firefox on my computer with Linux doesn't cause any problems either.

**Comment by thebaer** [comment] 2020-07-28 14:13
Thanks for the report! But I'm not able to replicate this, unfortunately. It looks like the icon font simply hasn't loaded yet... Could you try refreshing the page while on a good internet connection?

**Comment by Ravenbird** [comment] 2020-07-28 14:28
The screenshot ended when I was standing less than three meters away from my router with 50 Mbit internet connection and fast Wifi connection.  Unfortunately the error can still be reproduced here.

**Comment by thebaer** [comment] 2020-07-28 19:29
Can you take a look at the console with Firefox's remote debugging tools and let us know what you find? That will help determine the cause here so we can fix this.

**Comment by thebaer** [comment] 2020-09-02 13:49
Closing this since we don't have enough information to identify the cause of the issue and potentially fix it. Please feel free to submit more information and reopen this!

**Closed by thebaer** 2020-09-02 13:49 UTC
Labels: ❓ bug?
