### ISSUE TITLE
Naming a page "Tags" makes it impossible to edit

### ISSUE THREAD

**Issue by spritefullake** [writeas/writefreely#417] opened 2020-12-12 05:51 UTC
### Describe the bug
There is an error for any page with the starting text as 

``` # Tags ``` 

so that it is titled "Tags" when published to the blog. Pressing edit on the post from the blog page yields "This page is missing. Are you sure it was ever here?" as an error. I can only delete this page and rename it to avoid issues. 

### Steps to reproduce (if necessary)
1. Start a post with the first line as "# Tags" (without the quotes). You can optionally add content to the rest of the post but leave the first line as "# Tags"
2. Publish this post to your blog
3. View the post form the blog page and click edit
4. You will be encountered with page missing error

### Expected behavior
What should've happened?
I expected that I could name my page "Tags" without any issues. 
### Application configuration
 - **Single mode or Multi-user mode?** 
*Multi-user mode*
 - **Database?** [mysql/sqlite]
*mysql*
 - **Open registration?** [yes/no]
*yes*
 - **Federation enabled?** [yes/no]
*yes*
**Version or last commit**:
v0.12

**Comment by thebaer** [comment] 2020-12-12 15:33
Thanks for the report, @spritefullake! This is actually a duplicate of #305, which was fixed in #397. That'll be available in the next WriteFreely release!

**Closed by thebaer** 2020-12-12 15:33 UTC
