### ISSUE TITLE
Impossible to navigate to "/me/c/" via the UI

### ISSUE THREAD

**Issue by kuba-orlik** [writeas/writefreely#440] opened 2021-03-11 21:03 UTC
### Describe the bug

I'm running a single-user instance and I can't access the `/me/c/` via regular means - only by typing it directly in the address bar. There's no UI link that leads me to seemingly the only place where I can create a new blog on the same instance

### Steps to reproduce (if necessary)
1. Log in to a single-user instance
2. Try to find a button that takes me to the list of my blogs
3. There aren't any

### Expected behavior
There should be a "my blogs" button that takes me to the list of my blogs.

### Application configuration
 - Single mode
 - MySQL
 - Open registration
 - Federation enabled

**Version or last commit**: 0.12.0

**Comment by thebaer** [comment] 2021-03-11 21:10
Hey @kuba-orlik! This is indeed by design -- single-user here really means _single blog_ :slightly_smiling_face: 

If you'd like to create multiple blogs under your account, you'll want to switch to multi-user mode, disable registration, and increase the number of `max_blogs` in your `config.ini` (or via the admin dashboard on the web). With multi-user mode enabled, you'll be able to access the **Blogs** page via the web interface and create as many as you like.

I'll close this issue since it's not a bug, but please feel free to join us [on our forum](https://discuss.write.as/c/writefreely/15) if you need any help configuring WriteFreely for your situation, or if you want to discuss any design changes that might help you out.

**Closed by thebaer** 2021-03-11 21:10 UTC
Labels: not a bug
