### ISSUE TITLE
Cannot Creating User

### ISSUE THREAD

**Issue by mimikun** [writeas/writefreely#88] opened 2019-04-04 12:26 UTC
### Describe the bug
I was creating user in shell.
but, an error occurred.

Log:

```
hostname:~/writefreely$ ./writefreely -create-user user-name:pass_word

2019/04/04 12:10:43 Loading config.ini configuration...
2019/04/04 12:10:43 Connecting to mysql database...
2019/04/04 12:10:44 Creating user user-name...
ERROR: 2019/04/04 12:10:44 log.go:26: Rolling back users INSERT: Error 1364: Field 'created' doesn't have a default value
2019/04/04 12:10:44 Closing database connection...
ERROR: 2019/04/04 12:10:44 log.go:26: Unable to create user: Error 1364: Field 'created' doesn't have a default value
```

### Steps to reproduce (if necessary)
1. run `./writefreely -create-user user-name:pass_word`

### Application configuration
 - **Single mode or Multi-user mode?** Multi-user mode
 - **Database?** mysql
 - **Open registration?** no
 - **Federation enabled?** yes

**Version or last commit**:
  - v0.8.1

**Comment by thebaer** [comment] 2019-04-04 13:07
Which version of MySQL are you running? I believe this will happen in v5.5 or earlier.

**Comment by mimikun** [comment] 2019-04-04 14:07
I using MySQL 5.7.
mysql vesrion:
mysql  Ver 14.14 Distrib 5.7.25, for Linux (x86_64) using  EditLine wrapper

**Comment by mrvdb** [comment] 2019-04-04 14:21
Possibly related to #60

**Comment by thebaer** [comment] 2019-04-04 21:29
Hmm, yeah I'd say so. @mimikun are you building from source or using the compiled version we release? Maybe `schema.sql` is out of date? This is the important line that should prevent the error you're seeing: https://github.com/writeas/writefreely/blob/v0.8.1/schema.sql#L227

**Comment by mimikun** [comment] 2019-04-05 11:40
I'm using a released compiled version.
my `schema.sql` is [here](https://gist.github.com/mimikun/9cf92153371007885e80ccacfe64ff7f).

Should I update `schema.sql` and run `writefreely -migrate`?

**Comment by thebaer** [comment] 2019-04-05 15:02
Okay, if it's our release it'll use the embedded schema.sql. So I assume you're upgrading from a previous version? If so, this _is_ similar to #60 and not a bug.

To fix this, you'll have to manually update the database. I'd do:

```sql
ALTER TABLE `users` CHANGE `created` `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `accesstokens` CHANGE `created` `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;
```

I think that should cover everything, but let me know if anything still isn't working.

**Comment by thebaer** [comment] 2019-04-06 13:14
Closing this now, since it doesn't appear to be a bug. But feel free to continue discussing here.

**Closed by thebaer** 2019-04-06 13:14 UTC
Labels: not a bug, upgrade

**Comment by mimikun** [comment] 2019-04-06 23:30
I solved the way. 
thanks!

**Comment by thebaer** [comment] 2019-04-07 14:45
Awesome! No problem.
