### ISSUE TITLE
Anonymous posts moved to blogs are not being sent by Write.as Letters

### ISSUE THREAD

**Issue by cjeller1592** [writeas/writefreely#187] opened 2019-09-30 13:16 UTC
### Describe the bug
A common workflow for the [Write.as Email Subscriptions feature](https://write.as/letters): anonymous post moved to blog that enables email subscriptions. When this occurs, Write.as Letters does not send an email of the post to a subscriber.

From [digitalgyoza on the forum](https://discuss.write.as/t/new-in-labs-email-subscriptions/480/17?u=cjeller1592):

>Does this pick up anonymous posts that are then added to your blog? Or do you have to ensure the first time you publish the post is direct to your blog?
>
>I sometimes post as anonymous to check the format is correct etc, before making it live to my blog but I have a feeling the email subscription thing doesn’t pick this up in the same way. The entry I posted last night has not been sent to my email (which I used to test the subscription).

### Expected behavior

Write.as Letters should be picking up these moved posts and sending them to those who have subscribed to a blog via email.

**Comment by thebaer** [comment] 2019-10-18 15:00
This is fixed over on Write.as. Also marking as _not a bug_ since this isn't currently related to WriteFreely.

**Closed by thebaer** 2019-10-18 15:00 UTC
